import localFont from "next/font/local";
import "./globals.css";
import Footerand from "./components/Footerand";
import Navbar from "./components/Navbar";
import Header from "./components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-[130] leading-[1.2] !text-[var(--black)] bg-[var(--black)]`}
      >
         <div>
         <Header/>
         <Navbar/>
        {children}
        {/* <Footerand/> */}
      </div>
      </body>
    </html>
  );
}
